/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.DangKyDao;
import Helper.Confimr;
import Model.DangKy;

/**
 *
 * @author long
 */
public class SuaDichVu extends javax.swing.JFrame {

    private final String maDk;
    private final int soluong;
    private final String maKh;
    private final String maDichVu;

    /**
     * Creates new form SuaDichVu
     *
     * @param maKh
     * @param maDichVu
     * @param maDk
     * @param soluong
     */
    public SuaDichVu(String maKh, String maDichVu, String maDk, int soluong) {
        initComponents();
       
        
        this.maDk = maDk;
        this.soluong = soluong;
        this.maDichVu = maDichVu;
        this.maKh = maKh;
         this.Show();
        this.setLocationRelativeTo(null);
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        lblMaKhachHang = new javax.swing.JLabel();
        lblMaDichVu = new javax.swing.JLabel();
        cbSoLuong = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Mã Khách Hàng");

        jLabel2.setText("Số Lượng");

        jLabel3.setText("Mã Dịch Vụ");

        btnSua.setText("Submit");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        lblMaKhachHang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMaKhachHang.setText("jLabel4");

        lblMaDichVu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMaDichVu.setText("jLabel5");

        cbSoLuong.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K", "A", "Heo", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMaKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(lblMaDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbSoLuong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(btnSua)
                .addGap(158, 158, 158))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblMaKhachHang))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblMaDichVu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnSua)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        DangKy dk = dk();
        try {
             DangKyDao.upDateDichVu(dk);
             Confimr.alert(null, "thanh cong");
             dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
       
    }//GEN-LAST:event_btnSuaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JComboBox cbSoLuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblMaDichVu;
    private javax.swing.JLabel lblMaKhachHang;
    // End of variables declaration//GEN-END:variables
    DangKy dk() {
        DangKy dk = new DangKy();
        dk.setMaDk(maDk);
        dk.setMaDichVu(maDichVu);
        dk.setMaKhachHang(maKh);
        dk.setSoLuong(Integer.parseInt((String) cbSoLuong.getSelectedItem()));
        return dk;

    }
    private void Show()
    {
        lblMaDichVu.setText(maDichVu);
        lblMaKhachHang.setText(maKh);
        
    }
}
